// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmbcepywutbrhppxbwkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtYmNlcHl3dXRicmhwcHhid2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjMyMDYsImV4cCI6MjA2OTY5OTIwNn0.3ot0SzgqmjkX7bWZwHZ6ObmBMgIzbH5rt4cH8v_eGiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});